### ISSUE TITLE
character formatting issues on cygwin/git bash

### ISSUE THREAD

**Issue by tek0011** [Nawor3565/Windows-10-DeBloater#2]
might have some character issues running this in git/cygwin

![image](https://user-images.githubusercontent.com/1085020/31459168-f9d3a98c-ae87-11e7-8614-908f16b14297.png)

**Comment by tek0011** [comment]
nope.  its not git/cygwin.  Im not quite sure whats going on yet.  I cloned from git, and this is what its spitting out.

**Comment by Spunkie** [comment]
I had the same issue from a fresh clone here. Ended up changing the file encoding to ANSI, fixing the messed up characters, and then switched the file encoding back to UTF8.

**Comment by Nawor3565** [comment]
Ah, that's what I get for using Github's built-in text editor. I've fixed the file and I'll make a new commit right now. Thanks for the heads up.
